config/routes.rb
Moviereview::Application.routes.draw do
  resources :movie_items

  resources :carts

  resources :movies

  root 'store#index', as: "store"

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :movie_items,dependent: :destroy 
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :movie_items
validates :title, :release_year, :price, :description, :director, :stock, presence: true

validates :release_year, numericality: { only_integer: true }
validates :title, uniqueness: true
validates :stock, numericality: { only_integer: true }
validates :price, numericality: { greater_than_or_equal_to: 0.01 }
	if Rails.env.development?
		has_attached_file :poster, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg"	
	else
		has_attached_file :poster, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default.jpg",
							   :storage => :dropbox,
	  						   :dropbox_credentials => Rails.root.join("config/dropbox.yml")
	end
validates_attachment_content_type :poster, :content_type => /\Aimage\/.*\Z/
end

app/models/movie_item.rb
class MovieItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :movie
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  def index
    @carts = Cart.all
    respond_with(@carts)
  end

  def show
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.save
    respond_with(@cart)
  end

  def update
    @cart.update(cart_params)
    respond_with(@cart)
  end

  def destroy
    @cart.destroy
    respond_with(@cart)
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/controllers/movie_items_controller.rb
class MovieItemsController < ApplicationController
  before_action :set_movie_item, only: [:show, :edit, :update, :destroy]

  def index
    @movie_items = MovieItem.all
    respond_with(@movie_items)
  end

  def show
    respond_with(@movie_item)
  end

  def new
    @movie_item = MovieItem.new
    respond_with(@movie_item)
  end

  def edit
  end

  def create
    @movie_item = MovieItem.new(movie_item_params)
    @movie_item.save
    respond_with(@movie_item)
  end

  def update
    @movie_item.update(movie_item_params)
    respond_with(@movie_item)
  end

  def destroy
    @movie_item.destroy
    respond_with(@movie_item)
  end

  private
    def set_movie_item
      @movie_item = MovieItem.find(params[:id])
    end

    def movie_item_params
      params.require(:movie_item).permit(:movie_id, :cart_id, :quantity)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
respond_to:html
  def index
    @movies = Movie.all
    respond_with(@movies)
  end

  def show
    respond_with(@movie)
  end

  def new
    @movie = Movie.new
    respond_with(@movie)
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.save
    if @movie.save
      flash[:notice] ="Movie successfully created"
      respond_with(@movie)
    else
      render action: "new"
    end
  end

  def update
    if @movie.update(movie_params)
      flash[:notice] ="Movie successfully updated"
      respond_with(@movie)
    else
      render action: "edit"
    end
  end

  def destroy
    @movie.destroy
    respond_with(@movie)
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :release_year, :price, :description, :director,:stock, :poster)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message(type)
		type == :notice ? "alert-success" : "alert-danger"

		# case type
		# when :notice
		#  "alert-success"
		# when :alert
		#  "alert-danger"
		# else
		#   ""
		# end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/movie_items_helper.rb
module MovieItemsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
	def print_stock(stock)
		if stock == 0
			content_tag(:span, "Out of Stock", class: "out_stock")
		else
			content_tag(:span, "In Stock", class: "in_stock")
		end
	end
	
	def print_price(price)
		number_to_currency price
	end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user_id %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user_id %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_footer.html.erb
<footer class="row">
	<div class="col-md-12">
		<p>&copy; Movie Rewiew 2014</p>	
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MovieReview",store_path, class: "navbar-brand main-logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Register</a></li>
        <li><a href="#">Login</a></li> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do | type, message| %>
	<div class="alert <%= flash_message type %> alert-dismissible" role="alert">
  	<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<%= message %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviereview</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class ="container">
<%= render "layouts/header" %>
<%= render "layouts/messages" %>
</div>
<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>

app/views/movie_items/_form.html.erb
<%= form_for(@movie_item) do |f| %>
  <% if @movie_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_item.errors.count, "error") %> prohibited this movie_item from being saved:</h2>

      <ul>
      <% @movie_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_items/edit.html.erb
<h1>Editing movie_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_item %> |
<%= link_to 'Back', movie_items_path %>

app/views/movie_items/index.html.erb
<h1>Listing movie_items</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Cart</th>
      <th>Quantity</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_items.each do |movie_item| %>
      <tr>
        <td><%= movie_item.movie_id %></td>
        <td><%= movie_item.cart_id %></td>
        <td><%= movie_item.quantity %></td>
        <td><%= link_to 'Show', movie_item %></td>
        <td><%= link_to 'Edit', edit_movie_item_path(movie_item) %></td>
        <td><%= link_to 'Destroy', movie_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie item', new_movie_item_path %>

app/views/movie_items/new.html.erb
<h1>New movie_item</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_items_path %>

app/views/movie_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @movie_item.movie_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @movie_item.cart_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @movie_item.quantity %>
</p>

<%= link_to 'Edit', edit_movie_item_path(@movie_item) %> |
<%= link_to 'Back', movie_items_path %>

app/views/movies/_form.html.erb
<%= form_for(@movie,:html => { :multipart => true }) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation", class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden='true'>&times;</button>
      <h4><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h4>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :release_year %>
    <%= f.text_field :release_year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :director %>
    <%= f.text_field :director, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :stock %>
    <%= f.text_field :stock, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :poster %>
    <%= f.file_field :poster, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success custom-btn access" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1>All Movies</h1>

  <table class="table table-responsive">
  <thead>
    <tr>
    <th>Image</th>
      <th>Title</th>
      <th>Release year</th>
      <th>Price</th>
      <th>Description</th>
      <th>Director</th>
      <th>stock</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
       <td><%= image_tag movie.poster.url(:medium), class: "img-responsive"%></td>
        <td><%= movie.title %></td>
        <td><%= movie.release_year %></td>
        <td><%= print_price movie.price %></td>
        <td><%= movie.description %></td>
        <td><%= movie.director %></td>
        <td><%= movie.stock %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <br>

  <%= link_to 'New Movie', new_movie_path %>
</div>

app/views/movies/new.html.erb
<div class="container">
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <%= image_tag(@movie.poster.url, class: "img-responsive") %>
    </div>
      <div class="col-md-9">
    <h2><%= @movie.title %> (<%= @movie.release_year %>)</h2>
    <p><%= @movie.description %></p>
    <h4>Director: <%= @movie.director %></h4>
    <p>Price: <span class="movie_price"><%= @movie.price %></span> 
    | <%= link_to 'Back', store_path %></p>
    <p><%= link_to "Add to Cart", new_movie_item_path(movie_id: @movie.id), class: "btn btn-success custom-btn"%>
    </p>
      </div>
  </div>
  
</div>

app/views/store/index.html.erb
<div class="jumbotron">
  <div class="text-center">
    <h2>Welcome to <span id="app">Moviereview</span></h2>
    <p><strong>Buy</strong>, <strong>rate</strong> and <strong>review</strong> your favorite movies. <br> 
    Find new movies to watch based on you and your friends' taste.</p>
    <p><strong>Sign up</strong> using Facebook or Twitter</p>
    <p><%= link_to "Facebook", "#", class: "btn btn-primary btn-lg custom-btn-lg" %> <%= link_to "Twitter", "#", class: "btn btn-info btn-lg custom-btn-lg" %> <br> <span class="non-social"><strong>Don't use them?</strong> <ins><%= link_to "Sign up", "#" %></ins> with your email address.</span></p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4 class="tpad text-capitalize">Featured Movies</h4>
    </div>
  </div>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
        <%= link_to image_tag(movie.poster.url, class: "img-responsive"), movie %>
          </div>
          <div class="panel-body">
            <h4 class="text-center"><%= movie.title %> (<%= movie.release_year %>)</h4>
            <p><%= print_stock movie.stock %><span class="movie_price pull-right"><%= print_price movie.price %></span></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</di